"""Stage 6: normalise. Spec §5.7, §3.6.

Vocabulary dictionaries are generated by a model over the set of DISTINCT
values, never hand-written (two rounds of manual editing still left 14 percent
unmapped in the prototype). The mapping is then applied deterministically.
Raw values are never overwritten; canonical values land in a separate field
(rule 6.4).
"""

from __future__ import annotations

import datetime as dt
import json
from pathlib import Path
from typing import Any

from closeread.config import CommunityConfig, Settings
from closeread.jsonl import read_jsonl, write_jsonl

# value_set -> [(extraction_class, attribute)]
VALUE_SETS: dict[str, list[tuple[str, str]]] = {
    "assay_name": [("assay_platform", "assay_name"), ("object_format", "assay_name")],
    "platform": [("assay_platform", "platform")],
    "vendor": [("assay_platform", "vendor")],
    "format": [("object_format", "format")],
    "software": [("cell_typing", "software"), ("tme_algorithm", "software")],
    "algorithm": [("cell_typing", "algorithm"), ("tme_algorithm", "name")],
    "repository": [("data_availability", "repository")],
    "code_host": [("code_availability", "host")],
}

_SKIP = {None, "", "not_stated", "no_statement"}

BATCH_SIZE = 80

_RESPONSE_SCHEMA = {
    "type": "OBJECT",
    "properties": {
        "mappings": {
            "type": "ARRAY",
            "items": {
                "type": "OBJECT",
                "properties": {
                    "surface_form": {"type": "STRING"},
                    "canonical_form": {"type": "STRING"},
                },
                "required": ["surface_form", "canonical_form"],
            },
        }
    },
    "required": ["mappings"],
}


def _prompt(value_set: str, values: list[str]) -> str:
    return "\n".join(
        [
            f"You are canonicalising `{value_set}` values extracted from scientific publications.",
            "For each surface form below, give a canonical form. Rules:",
            "1. Merge trivial variants: case, punctuation, pluralisation, vendor prefixes,",
            "   version suffixes (e.g. 'Seurat v4' -> 'Seurat').",
            "2. NEVER merge genuinely distinct things. OME-TIFF is not TIFF. Leiden is not",
            "   PhenoGraph. CODEX is not CyCIF. When unsure, keep the surface form as its",
            "   own canonical form.",
            "3. Use the most widely recognised name as the canonical form.",
            "4. Return every surface form exactly once, spelled exactly as given.",
            "",
            "Surface forms:",
            json.dumps(values, ensure_ascii=False, indent=0),
        ]
    )


def collect_distinct_values(
    settings: Settings, community: str, value_set: str
) -> list[str]:
    pairs = VALUE_SETS[value_set]
    values: set[str] = set()
    for path in sorted((settings.community_dir(community) / "bronze").glob("records_*.jsonl")):
        for r in read_jsonl(path):
            for cls, attr in pairs:
                if r["extraction_class"] == cls:
                    v = r["attributes"].get(attr)
                    for el in v if isinstance(v, list) else [v]:
                        if el not in _SKIP:
                            values.add(str(el))
    return sorted(values)


def vocab_map_path(settings: Settings, community: str) -> Path:
    return settings.community_dir(community) / "vocab_map.jsonl"


def load_vocab_map(settings: Settings, community: str) -> dict[tuple[str, str], str]:
    path = vocab_map_path(settings, community)
    mapping: dict[tuple[str, str], str] = {}
    if path.exists():
        for row in read_jsonl(path):
            mapping[(row["value_set"], row["surface_form"])] = row["canonical_form"]
    return mapping


def generate_mapping(
    settings: Settings, community: str, value_set: str, model: str, log=print
) -> int:
    """Ask a model for canonical forms of unmapped distinct values; merge into
    vocab_map.jsonl. Cost scales with distinct values, not records."""
    from closeread.extract.batch import _client

    distinct = collect_distinct_values(settings, community, value_set)
    existing = load_vocab_map(settings, community)
    todo = [v for v in distinct if (value_set, v) not in existing]
    log(f"{value_set}: {len(distinct)} distinct values, {len(todo)} unmapped")
    if not todo:
        return 0

    client = _client()
    version = dt.date.today().isoformat()
    new_rows: list[dict[str, Any]] = []
    for i in range(0, len(todo), BATCH_SIZE):
        chunk = todo[i : i + BATCH_SIZE]
        resp = client.models.generate_content(
            model=model,
            contents=_prompt(value_set, chunk),
            config={
                "response_mime_type": "application/json",
                "response_schema": _RESPONSE_SCHEMA,
                "temperature": 0,
            },
        )
        payload = json.loads(resp.text)
        got = {m["surface_form"]: m["canonical_form"] for m in payload["mappings"]}
        for v in chunk:
            canonical = got.get(v, v)  # unanswered forms map to themselves
            new_rows.append(
                {
                    "value_set": value_set,
                    "surface_form": v,
                    "canonical_form": canonical,
                    "mapping_version": version,
                }
            )
    path = vocab_map_path(settings, community)
    prior = list(read_jsonl(path)) if path.exists() else []
    write_jsonl(path, prior + new_rows)
    log(f"{value_set}: wrote {len(new_rows)} new mappings -> {path}")
    return len(new_rows)


def apply_to_silver(settings: Settings, community: str, log=print) -> None:
    """Rebuild silver from bronze + vocab map + judge verdicts, deterministically.
    Changing a vocabulary rebuilds silver; it never requires re-extraction (§4.3)."""
    mapping = load_vocab_map(settings, community)
    out_dir = settings.community_dir(community)
    verdicts: dict[str, dict[str, Any]] = {}
    for vp in sorted((out_dir / "judge").glob("verdicts_*.jsonl")) if (out_dir / "judge").exists() else []:
        for v in read_jsonl(vp):
            verdicts[v["record_id"]] = v

    attr_sets: dict[str, list[tuple[str, str]]] = {}
    for vs, pairs in VALUE_SETS.items():
        for cls, attr in pairs:
            attr_sets.setdefault(cls, []).append((vs, attr))

    silver_dir = out_dir / "silver"
    for path in sorted((out_dir / "bronze").glob("records_*.jsonl")):
        rows = []
        for r in read_jsonl(path):
            canonical: dict[str, Any] = {}
            for vs, attr in attr_sets.get(r["extraction_class"], []):
                v = r["attributes"].get(attr)
                if isinstance(v, list):
                    canonical[attr] = [mapping.get((vs, str(el)), str(el)) for el in v if el not in _SKIP]
                elif v not in _SKIP:
                    canonical[attr] = mapping.get((vs, str(v)), str(v))
            if canonical:
                r["attributes_canonical"] = canonical
            verdict = verdicts.get(r["record_id"])
            if verdict:
                r["judge_verdict"] = verdict["verdict"]
                r["judge_confidence"] = verdict.get("confidence")
                r["judge_reason"] = verdict.get("reason")
            rows.append(r)
        write_jsonl(silver_dir / path.name, rows)
    log(f"silver rebuilt -> {silver_dir}")
